[package]
name = "soccer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bevy_egui = "0.12"
bevy-inspector-egui = "0.9.0"
bevy_prototype_lyon = "0.4"
chrono = "0.4"
