[package]
name = "west-world-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
chrono = "0.4"
paste = "1.0"
rand = "0.8"
