use bevy::app::PluginGroupBuilder;
use bevy::core::FixedTimestep;
use bevy::ecs::schedule::ShouldRun;
use bevy::prelude::*;

use crate::components::physics::PHYSICS_STEP;
use crate::components::team::*;
use crate::events::*;
use crate::game::team::*;
use crate::states;
use crate::states::*;
use crate::systems;
use crate::systems::Systems;
use crate::AGENT_UPDATE_STEP;

pub struct StatesPlugins;

impl PluginGroup for StatesPlugins {
    fn build(&mut self, group: &mut PluginGroupBuilder) {
        group.add(IntroStatePlugin).add(MainStatePlugin);
    }
}

struct IntroStatePlugin;

impl Plugin for IntroStatePlugin {
    fn build(&self, app: &mut App) {
        // systems
        app.add_system_set(SystemSet::on_enter(GameState::Intro).with_system(states::intro::setup))
            .add_system_set(
                SystemSet::on_update(GameState::Intro).with_system(states::intro::button_handler),
            )
            .add_system_set(
                SystemSet::on_exit(GameState::Intro).with_system(states::intro::teardown),
            );
    }
}

struct MainStatePlugin;

impl Plugin for MainStatePlugin {
    fn build(&self, app: &mut App) {
        // plugins
        app.add_plugin(crate::components::team::SoccerTeamStateMachinePlugin)
            .add_plugin(crate::components::team::FieldPlayerStateMachinePlugin)
            .add_plugin(crate::components::team::GoalKeeperStateMachinePlugin);

        // events
        app.add_event::<FindSupportEvent>()
            .add_event::<GoalScoredEvent>()
            .add_event::<FieldPlayerDispatchedMessageEvent>()
            .add_event::<GoalKeeperDispatchedMessageEvent>();

        // systems
        app.add_system_set(SystemSet::on_enter(GameState::Main).with_system(states::main::setup))
            // physics (fixed timestep)
            .add_system_set(
                // https://github.com/bevyengine/bevy/issues/1839
                SystemSet::new()
                    .with_run_criteria(FixedTimestep::step(PHYSICS_STEP as f64).chain(
                        |In(input): In<ShouldRun>, state: Res<State<GameState>>| {
                            if state.current() == &GameState::Main {
                                input
                            } else {
                                ShouldRun::No
                            }
                        },
                    ))
                    /*SystemSet::on_update(GameState::Main)
                    .with_run_criteria(FixedTimestep::step(PHYSICS_STEP as f64))*/
                    // steering
                    .with_system(systems::steering::update_seek.label(Systems::Steering))
                    .with_system(systems::steering::update_arrive.label(Systems::Steering))
                    .with_system(systems::steering::update_pursuit.label(Systems::Steering))
                    .with_system(
                        systems::steering::update
                            .label(Systems::SteeringUpdatePhysics)
                            .after(Systems::Steering),
                    )
                    .with_system(systems::steering::update_interpose.label(Systems::Steering))
                    .with_system(systems::steering::update_separation.label(Systems::Steering))
                    // physics
                    .with_system(
                        systems::physics::update
                            .label(Systems::Physics)
                            .after(Systems::SteeringUpdatePhysics),
                    )
                    .with_system(systems::physics::facing.after(Systems::Physics))
                    // field player systems
                    .with_system(
                        systems::team::field_player::update_physics::<RedTeam>
                            .after(Systems::Steering)
                            .before(Systems::SteeringUpdatePhysics),
                    )
                    .with_system(
                        systems::team::field_player::update_physics::<BlueTeam>
                            .after(Systems::Steering)
                            .before(Systems::SteeringUpdatePhysics),
                    )
                    // everything else
                    .with_system(systems::ball::update_physics),
            )
            // agents (fixed timestep)
            .add_system_set(
                // https://github.com/bevyengine/bevy/issues/1839
                SystemSet::new()
                    .with_run_criteria(FixedTimestep::step(AGENT_UPDATE_STEP as f64).chain(
                        |In(input): In<ShouldRun>, state: Res<State<GameState>>| {
                            if state.current() == &GameState::Main {
                                input
                            } else {
                                ShouldRun::No
                            }
                        },
                    ))
                    /*SystemSet::on_update(GameState::Main)
                    .with_run_criteria(FixedTimestep::step(AGENT_UPDATE_STEP))*/
                    // messaging
                    .with_system(systems::messaging::update::<FieldPlayerMessage>)
                    .with_system(systems::messaging::update::<GoalKeeperMessage>)
                    // team systems
                    .with_system(
                        systems::team::PrepareForKickOff_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::TeamStates)
                            .after(Systems::GlobalStateExecute),
                    )
                    .with_system(
                        systems::team::PrepareForKickOff_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::TeamStates)
                            .after(Systems::GlobalStateExecute),
                    )
                    .with_system(
                        systems::team::Defending_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::TeamStates)
                            .after(Systems::GlobalStateExecute),
                    )
                    .with_system(
                        systems::team::Defending_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::TeamStates)
                            .after(Systems::GlobalStateExecute),
                    )
                    .with_system(
                        systems::team::Attacking_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::TeamStates)
                            .after(Systems::GlobalStateExecute),
                    )
                    .with_system(
                        systems::team::Attacking_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::TeamStates)
                            .after(Systems::GlobalStateExecute),
                    )
                    // field player systems
                    .with_system(
                        systems::team::field_player::GlobalState_execute::<RedTeam>
                            .label(Systems::GlobalStateExecute),
                    )
                    .with_system(
                        systems::team::field_player::GlobalState_execute::<BlueTeam>
                            .label(Systems::GlobalStateExecute),
                    )
                    .with_system(
                        systems::team::field_player::ChaseBall_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ChaseBall_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Wait_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Wait_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReceiveBall_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReceiveBall_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::KickBall_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::KickBall_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Dribble_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Dribble_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::SupportAttacker_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::SupportAttacker_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReturnToHomeRegion_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReturnToHomeRegion_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    // goal keeper systems
                    .with_system(
                        systems::team::goal_keeper::TendGoal_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::TendGoal_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::ReturnHome_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::ReturnHome_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::InterceptBall_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::InterceptBall_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::PutBallBackInPlay_execute::<RedTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::PutBallBackInPlay_execute::<BlueTeam>
                            .label(Systems::StateExecute)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    ),
            )
            // per-frame systems
            .add_system_set(
                SystemSet::on_update(GameState::Main)
                    // steering
                    .with_system(systems::steering::update_debug)
                    // team systems
                    .with_system(systems::team::update::<RedTeam>.label(Systems::TeamUpdate))
                    .with_system(systems::team::update::<BlueTeam>.label(Systems::TeamUpdate))
                    .with_system(
                        systems::team::PrepareForKickOff_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::PrepareForKickOff_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::PrepareForKickOff_exit::<RedTeam>
                            .label(Systems::StateExit)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::PrepareForKickOff_exit::<BlueTeam>
                            .label(Systems::StateExit)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::Defending_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::Defending_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::Attacking_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::Attacking_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::Attacking_exit::<RedTeam>
                            .label(Systems::StateExit)
                            .label(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::Attacking_exit::<BlueTeam>
                            .label(Systems::StateExit)
                            .label(Systems::TeamStates),
                    )
                    // field player systems
                    .with_system(
                        systems::team::field_player::update::<RedTeam>
                            .label(Systems::FieldPlayerUpdate)
                            .after(Systems::TeamUpdate),
                    )
                    .with_system(
                        systems::team::field_player::update::<BlueTeam>
                            .label(Systems::FieldPlayerUpdate)
                            .after(Systems::TeamUpdate),
                    )
                    .with_system(
                        systems::team::field_player::find_support_event_handler::<RedTeam>
                            .label(Systems::FieldPlayerEvents)
                            .after(Systems::FieldPlayerStates),
                    )
                    .with_system(
                        systems::team::field_player::find_support_event_handler::<BlueTeam>
                            .label(Systems::FieldPlayerEvents)
                            .after(Systems::FieldPlayerStates),
                    )
                    .with_system(
                        systems::team::field_player::GlobalState_on_message::<RedTeam>
                            .label(Systems::GlobalStateOnMessage),
                    )
                    .with_system(
                        systems::team::field_player::GlobalState_on_message::<BlueTeam>
                            .label(Systems::GlobalStateOnMessage),
                    )
                    .with_system(
                        systems::team::field_player::ChaseBall_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ChaseBall_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ChaseBall_exit::<RedTeam>
                            .label(Systems::StateExit)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ChaseBall_exit::<BlueTeam>
                            .label(Systems::StateExit)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Wait_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Wait_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReceiveBall_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReceiveBall_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReceiveBall_exit::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReceiveBall_exit::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::KickBall_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::KickBall_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Dribble_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::Dribble_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::SupportAttacker_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::SupportAttacker_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::SupportAttacker_exit::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::SupportAttacker_exit::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReturnToHomeRegion_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReturnToHomeRegion_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReturnToHomeRegion_exit::<RedTeam>
                            .label(Systems::StateExit)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::field_player::ReturnToHomeRegion_exit::<BlueTeam>
                            .label(Systems::StateExit)
                            .label(Systems::FieldPlayerStates)
                            .after(Systems::TeamStates),
                    )
                    // goal keeper systems
                    .with_system(
                        systems::team::goal_keeper::update::<RedTeam>
                            .label(Systems::GoalKeeperUpdate)
                            .after(Systems::TeamUpdate),
                    )
                    .with_system(
                        systems::team::goal_keeper::update::<BlueTeam>
                            .label(Systems::GoalKeeperUpdate)
                            .after(Systems::TeamUpdate),
                    )
                    .with_system(
                        systems::team::goal_keeper::GlobalState_on_message::<RedTeam>
                            .label(Systems::GlobalStateOnMessage),
                    )
                    .with_system(
                        systems::team::goal_keeper::GlobalState_on_message::<BlueTeam>
                            .label(Systems::GlobalStateOnMessage),
                    )
                    .with_system(
                        systems::team::goal_keeper::TendGoal_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::TendGoal_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::TendGoal_exit::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::TendGoal_exit::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::ReturnHome_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::ReturnHome_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::ReturnHome_exit::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::ReturnHome_exit::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::InterceptBall_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::InterceptBall_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::InterceptBall_exit::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::InterceptBall_exit::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::PutBallBackInPlay_enter::<RedTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    .with_system(
                        systems::team::goal_keeper::PutBallBackInPlay_enter::<BlueTeam>
                            .label(Systems::StateEnter)
                            .label(Systems::GoalKeeperStates)
                            .after(Systems::TeamStates),
                    )
                    // everything else
                    .with_system(systems::ball::update)
                    .with_system(systems::goal::update::<RedTeam>.label(Systems::GoalUpdate))
                    .with_system(systems::goal::update::<BlueTeam>.label(Systems::GoalUpdate))
                    .with_system(systems::goal_scored_event_handler.after(Systems::GoalUpdate)),
            )
            .add_system_set(
                SystemSet::on_exit(GameState::Main).with_system(states::main::teardown),
            );
    }
}
